import type { Metadata } from "next";
import "./globals.scss";
import { Header } from "@/components/header";
import { NextIntlClientProvider, useTranslations } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
import { connectDB } from "@/lib/mongodb";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();

  const messages = await getMessages();
  return (
    <html lang={locale}>
      <title>Cool workouts</title>
      <body>
        <NextIntlClientProvider messages={messages}>
          <Header />
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
